jei = true
craftingcraft = true
toms_storage = true
storagenetwork = true
cyclic = true
sophisticatedbackpacks = true
sophisticatedcore = true
ironfurnaces = true
fastfurnace = true
fastbench = true
fastsuite = true
prettypipes = true
refinedstorage = true
refinedstorageaddons = true
ae2 = true
extendedcrafting = true
tconstruct = true
occultism = true

